---
title: "Final working doc"
format: html
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
library(leaflet)
```

# data tidying

```{r}
nhl_full_years <- nhl_full_years |>
  rename(PTS_PCT = `PTS%`,
         RPt_PCT = `RPt%`,
         RgPT_PCT = `RgPt%`) |>
  mutate(across(GP:RW, as.numeric),
         RgPT_PCT = as.numeric(RgPT_PCT),
         season = as.factor(season))

 nhl_full_years |>
    filter(Team %in% c("Minnesota Wild", "St. Louis Blues")) |>
    ggplot(aes(x = season, y = W, color = Team)) +
    geom_point() +
    geom_smooth()
```


# map thing
```{r}
locations_clean <- locations_clean |>
  rename(Team = team)

nhl_map <- nhl_full_years |>
  filter(season == 2026) |>
  mutate(Team = str_replace(Team, "\\*", ""),
         W_PCT = (as.numeric(W) / as.numeric(GP)) * 100,
         W_PCT = round(W_PCT, 2),
         W_PCT_map = (as.numeric(W) / as.numeric(GP)) * 30,
         popup = str_c(arena, ", the ", Team, " have a win percentage of ", W_PCT, "%")) |>
  full_join(locations_clean) 


```

```{r}
bins <- c(0, 30, 40, 50, 60, 70, 80, 100)
pal <- colorBin("YlOrRd", domain = nhl_map$W_PCT, bins = bins)

leaflet() |>
  setView(-97, 40, 4) |>
  addTiles() |>
  addCircleMarkers(data = nhl_map,
        lat = ~ latitude, 
        lng = ~ longitude,
        popup = ~ popup,
        radius = ~ W_PCT_map,
        weight = 4,
        color = "black",
        fillColor = ~pal(W_PCT),
        fillOpacity = 1) 
# addLegend not working
```

# line plot

```{r}
nhl_full_years |>
  filter(Team %in% c("Minnesota Wild", "St. Louis Blues", "Colorado Avalanche")) |>
  ggplot(aes(x = season, y = W, color = Team)) +
  geom_point() +
  geom_smooth(method = loess)

nhl_full_years |>
  filter(Team == "Minnesota Wild") |>
  select(Team, W, season)
```

